redis :
    host : 'redis://127.0.0.1:6379'
    max-total: 1100
    max-idle: 16
    min-idle: 16
    idle-time: 60
    eviction: 30
    tests: 3

ext :
    integration_id : '<integration_id>'
    api_key : '<api_key>'
    api_secret : '<api_secret>'
    scopes : '<scopes>'
    base_url : '<base_url>'
    access_mode : '<offline/online>'
    cluster: 'https://api.fynd.com'

    # Example
    # integration_id : '123'
    # api_key : 'dsdofij340jfis'
    # api_secret : '92hueuf9'
    # scopes : 'company/saleschannel'
    # base_url : 'https://4870-27-109-3-234.in.ngrok.io'
    # access_mode : 'offline'
    # cluster: 'https://api.fynd.com'